import React from 'react';
import { Link } from 'react-router-dom';
import { Brain, Layers, MessageSquare, Globe, Puzzle, Swords, BookOpen, Bot } from 'lucide-react';
import './AIGames.css';

const AIGames = () => {
    const games = [
        { id: 1, title: 'AI Quiz Generator', description: 'Generate custom quizzes from any topic instantly.', icon: <Brain size={32} strokeWidth={1.5} />, color: '#3b82f6' },
        { id: 2, title: 'AI Flashcard Battle', description: 'Compete against the AI in rapid-fire flashcard rounds.', icon: <Layers size={32} strokeWidth={1.5} />, color: '#8b5cf6', comingSoon: true },
        { id: 3, title: 'AI Debate Game', description: 'Hone your argumentation skills against an AI opponent.', icon: <MessageSquare size={32} strokeWidth={1.5} />, color: '#ec4899', comingSoon: true },
        { id: 4, title: 'AI Scenario Simulator', description: 'Navigate complex real-world scenarios generated by AI.', icon: <Globe size={32} strokeWidth={1.5} />, color: '#10b981', comingSoon: true },
        { id: 5, title: 'AI Puzzle Generator', description: 'Solve intricate puzzles tailored to your skill level.', icon: <Puzzle size={32} strokeWidth={1.5} />, color: '#f59e0b', comingSoon: true },
        { id: 6, title: 'AI Boss Battle', description: 'Face off against ultimate academic challenges.', icon: <Swords size={32} strokeWidth={1.5} />, color: '#ef4444', comingSoon: true },
        { id: 7, title: 'AI Story-Based Learning', description: 'Learn through engaging, AI-crafted interactive narratives.', icon: <BookOpen size={32} strokeWidth={1.5} />, color: '#6366f1', comingSoon: true },
        { id: 8, title: 'AI Study Companion', description: 'Your personal AI tutor for 24/7 academic support.', icon: <Bot size={32} strokeWidth={1.5} />, color: '#14b8a6', comingSoon: true },
    ];

    return (
        <div className="games-page">
            <div className="container">
                <div className="games-header animate-fade-in-up">
                    <h1 className="games-title">
                        <span className="text-gradient-primary">AI Games</span> Library
                    </h1>
                    <p className="games-subtitle text-secondary">
                        Choose from our collection of interactive AI-powered learning experiences.
                    </p>
                </div>

                <div className="games-grid">
                    {games.map((game, index) => (
                        <div
                            key={game.id}
                            className={`game-card delay-${(index % 3) + 1} animate-fade-in-up ${game.comingSoon ? 'coming-soon' : ''}`}
                            style={{ '--game-color': game.color }}
                        >
                            <div className="game-card-bg"></div>
                            {game.comingSoon && <div className="coming-soon-badge">Coming Soon</div>}
                            <div className="game-icon">
                                {game.icon}
                            </div>
                            <h3 className="game-title">{game.title}</h3>
                            <p className="game-description">{game.description}</p>

                            {game.comingSoon ? (
                                <button className="btn-primary play-btn disabled" disabled>
                                    Coming Soon
                                </button>
                            ) : (
                                <Link to={`/games/${game.id}/setup`} className="btn-primary play-btn" style={{ textDecoration: 'none', textAlign: 'center' }}>
                                    Play Now
                                </Link>
                            )}
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default AIGames;
