/**
 * Single source of truth for the game catalogue.
 *
 * The library page, the settings service and the admin area all read from here so
 * a game can never be listed in one place and missing from another.
 */
export const GAMES = [
    {
        id: 1,
        title: 'AI Quiz Generator',
        description: 'Generate custom quizzes from any topic instantly.',
        iconKey: 'quiz',
        color: '#3b82f6',
        collection: 'quizzes',
        resultGameType: 'AI Quiz Generator',
        opensCompanion: false
    },
    {
        id: 2,
        title: 'AI Flashcard Battle',
        description: 'Compete against the AI in rapid-fire flashcard rounds.',
        iconKey: 'flashcards',
        color: '#8b5cf6',
        collection: 'flashcards',
        resultGameType: 'AI Flashcard Battle',
        opensCompanion: false
    },
    {
        id: 3,
        title: 'AI Debate Game',
        description: 'Hone your argumentation skills against an AI opponent.',
        iconKey: 'debate',
        color: '#ec4899',
        collection: 'debates',
        resultGameType: 'AI Debate Game',
        opensCompanion: false
    },
    {
        id: 4,
        title: 'AI Scenario Simulator',
        description: 'Navigate complex real-world scenarios generated by AI.',
        iconKey: 'scenario',
        color: '#10b981',
        collection: 'scenarios',
        resultGameType: 'AI Scenario Simulator',
        opensCompanion: false
    },
    {
        id: 5,
        title: 'AI Puzzle Generator',
        description: 'Solve intricate puzzles tailored to your skill level.',
        iconKey: 'puzzle',
        color: '#f59e0b',
        collection: 'puzzles',
        resultGameType: 'AI Puzzle Generator',
        opensCompanion: false
    },
    {
        id: 6,
        title: 'AI Boss Battle',
        description: 'Face off against ultimate academic challenges.',
        iconKey: 'boss',
        color: '#ef4444',
        collection: 'bosses',
        resultGameType: 'AI Boss Battle',
        opensCompanion: false
    },
    {
        id: 7,
        title: 'AI Story-Based Learning',
        description: 'Learn through engaging, AI-crafted interactive narratives.',
        iconKey: 'story',
        color: '#6366f1',
        collection: null,
        resultGameType: 'AI Story-Based Learning',
        opensCompanion: false,
        comingSoonByDefault: true
    },
    {
        id: 8,
        title: 'AI Study Companion',
        description: 'Your personal AI tutor for 24/7 academic support.',
        iconKey: 'companion',
        color: '#14b8a6',
        collection: 'companion_sessions',
        resultGameType: 'AI Study Companion',
        opensCompanion: true
    }
];

export const getGameById = (id) => GAMES.find((game) => game.id === Number(id)) || null;

/**
 * Merges admin overrides over the defaults baked into the catalogue.
 *
 * @param {{games?: Record<string, {enabled?: boolean, comingSoon?: boolean}>}} settings
 * @returns {Record<string, {enabled: boolean, comingSoon: boolean}>} Keyed by game id.
 */
export const resolveGameAvailability = (settings) => {
    const stored = settings?.games || {};

    return GAMES.reduce((acc, game) => {
        const override = stored[game.id] || stored[String(game.id)] || {};
        acc[game.id] = {
            enabled: override.enabled !== undefined ? Boolean(override.enabled) : true,
            comingSoon: override.comingSoon !== undefined ? Boolean(override.comingSoon) : Boolean(game.comingSoonByDefault)
        };
        return acc;
    }, {});
};